// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtyjgzhzqhycawplowud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10eWpnemh6cWh5Y2F3cGxvd3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MzA1MzQsImV4cCI6MjA2NzQwNjUzNH0.ppcXv3pYCreSR45u3p0r3rOvtstqnc1ZHg15xKyn6rw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});